version: '3.8'
services:
  db:
    image: mysql:8.0.29
    command: mysqld --default_authentication_plugin=mysql_native_password
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: MySql2023
      MYSQL_USER: usr_mysql
      MYSQL_PASSWORD: mysql2023
      MYSQL_DATABASE: mysqldatabase
    ports:
      - 3306
    networks:
      - wordpress-network
    volumes:
      - mysql_wordpress:/var/lib/mysql
 
  wordpress:
    image: wordpress:latest
    environment:
      TZ: America/Sao_Paulo
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: mysqldatabase
      WORDPRESS_DB_USER: usr_mysql
      WORDPRESS_DB_PASSWORD: mysql2023
    ports:
      - 8080:80
    networks:
      - wordpress-network
 
networks:
    wordpress-network:
      driver: bridge

volumes:
  mysql_wordpress: