version: "3.7"

services: 
  influxdb:
    image: influxdb:1.8
    environment: 
      DOCKER_INFLUXDB_INIT_MODE: "upgrade"
      DOCKER_INFLUXDB_INIT_USERNAME: "influx"
      DOCKER_INFLUXDB_INIT_PASSWORD: "influx2021"
      DOCKER_INFLUXDB_INIT_ORG: "docker-influx"
      DOCKER_INFLUXDB_INIT_BUCKET: "docker-influx"
    ports:
      - "8086:8086"
    volumes:
      - /var/lib/influxdb